—-
- name: Playbook to create gce load balancing instance
  hosts: localhost
  connection: local
  gather_facts: True

  vars:
     service_account_email: <Your gce service account email>
     credentials_file: <Your json credentials file>
     project_id: <Your project id>

 tasks:
    - name: Create gce load balancer
    gce_lb:
      name: lbserver
      state: present
      region: us-central1
      members: ['us-central1-a/web1','us-central1-a/web2','us-central1-a/web3']
      httphealthcheck_name: hc
      httphealthcheck_port: 80
      httphealthcheck_path: "/"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
