---
# apt module requires aptitude
- hosts: localhost
  become_method: sudo
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: apt update system
      user: name=ansible state=present
